version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    build: ./webapp
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./webapp:/qrnote
    ports:
      - "3000:3000"
    depends_on:
      - db

